{%set name = "PyTrie" %}
{%set version = "0.3" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "0c1bd0cb7c301b193da4bcf31bdf68bbdbea88be4bea5f680caecc56d9b74020" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sortedcontainers

test:
  imports:
    - pytrie
  
about:
  home: https://github.com/gsakkis/pytrie
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A pure Python implementation of the trie data structure.'
  dev_url: https://github.com/gsakkis/pytrie
  doc_url: https://pytrie.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
